### ISSUE TITLE
Empty page of Videos shows "Favourite" empty page

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/files_filter#4]
If there are no Videos the empty page looks like the empty page of Favourite:

![bildschirmfoto 2017-06-13 um 14 53 39](https://user-images.githubusercontent.com/245432/27101632-2de71504-5048-11e7-87df-dcea953d735d.png)

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @nickvergessen @icewind1991

**Comment by nickvergessen** [comment]
The links seem to not change anything at all

**Comment by nickvergessen** [comment]
#5

**Comment by icewind1991** [comment]
this is unrelated
